### PR TITLE
Remove required keys, to support IAM roles

### LINKED ISSUE #29: Support IAM Roles
This plugin should not require `accessKeyId` and `secretAccessKey` outright.  The default behavior of `aws-sdk` is to load temporary keys from an IAM Role if one exists.  Our deploy tooling runs `ember deploy production` on an instance running in our VPC with a role and as such should not require a static set of keys.

### PR DESCRIPTION
**Pull request by kkumler**
Not specifying the access key id and secret access key to allow aws-sdk to load from the EC2 instance profile.
Fixes #29

### CODE REVIEW

**Comment by tomdale** [comment]
Similarly, I'd like to be able to specify a profile I have saved with the AWS CLI in lieu of the credentials.

**Comment by ghedamat** [comment]
thanks @kkumler !

just one tiny thing, maybe clarify in the readme that the secret is to be used in combo with the access key and not with the IAM role? I know it seems obvious but it's probably better to be explicit just in case.

@tomdale shall we do what you suggest as part of a separate PR? (I assume `aws-sdk` will allow us to support your use case)

**Comment by kkumler** [comment]
@ghedamat Sure, I'll update the readme a bit more for that.

I'll keep this PR to just this change, but I could refactor things a bit and include functionality for all authentication options more cleanly, in a separate PR.

**Comment by ghedamat** [comment]
@kkumler sounds like a plan!

**Comment by tomdale** [comment]
@ghedamat It looks like the AWS SDK respects the `AWS_PROFILE` environment variable, so long as `ember-cli-deploy-s3` isn't manually overriding anything: http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html#Using_Profiles_with_the_SDK

**Comment by kkumler** [comment]
Yep. I was thinking that would cover most everyone's use case. It'll be
part of the readme update here.

## 

Kris

**Comment by lukemelia** [comment]
:+1: looks good!

**Comment by ghedamat** [comment]
thanks @kkumler !

**Pull request merged**
