### PR TITLE
Set ContentMD5 header

### LINKED ISSUE #9: Set Content-MD5 header so we get verification by S3 that upload was not corrupted
For more info: http://stackoverflow.com/a/8622823/614844

### PR DESCRIPTION
**Pull request by achambers**
Closes #9

### CODE REVIEW

**Comment by lukemelia** [comment]
Why only for images?

**Comment by achambers** [comment]
@lukemelia Only because images were crapping out when I was testing it. I haven't done that before. What file types should I be doing this for?

**Comment by lukemelia** [comment]
Ah, I misread, you are _excluding_ images.

We should we doing this for all files, and should not be stringifying first. Example implementations in node:

https://gist.github.com/sandfox/1370593#file-node-s3-js-L443

There's also a suggestion in the docs that the aws sdk can do this for us? If so, we should do that.

**Comment by achambers** [comment]
Ah ok. Got some work to do still. I won't be back online proper until
Sunday so will take a look then. Thanks.

**Comment by achambers** [comment]
@lukemelia My understanding of these two pages suggest that the checksum is automatically calculated by default. What are your thoughts? (search for `computeChecksums` on both pages)

https://aws.amazon.com/releasenotes/JavaScript/6967335344676381
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html

**Comment by achambers** [comment]
@lukemelia Based on this test, I think the checksums are being calculated without us making any changes at all. Do you agree?

https://github.com/aws/aws-sdk-js/blob/6891066e37f3cab978fd0d2f7d4395d4a03fe26f/test/services/s3.spec.coffee#L537-L608

**Comment by achambers** [comment]
Closing as this currently is already done automatically by the aws-sdk library

**Pull request closed without merging**
