### PR TITLE
Dependency Upgrades

### PR DESCRIPTION
**Pull request by kturney**
## What Changed & Why
Dependency upgrades and a few code changes to work with the upgraded deps.

### CODE REVIEW

**Comment by lukemelia** [comment]
@kturney I think we're not quite ready to drop Node 0.12 support as we want to continue to support older ember-cli versions that may be in use with it.

**Comment by lukemelia** [comment]
@kturney Besides that, this is looking good. Thanks for tackling it!

**Comment by kturney** [comment]
whoops. Sorry. Missed the 0.12 support drop from core-object. I moved back to 2

**Comment by kturney** [comment]
@lukemelia any idea why using the same version of core-object as ember-cli-deploy fails here but not there? Maybe 2.0.X is cached on ember-cli-deploy? Should they both be locked to `~2.0.0`?

**Comment by lukemelia** [comment]
@kturney not sure. I just kicked the build to see if that does it. We may need to clear the travis cache too.

**Comment by lukemelia** [comment]
Thanks for persevering @kturney!

**Pull request merged**
