### PR TITLE
update mime dependency to 2.x in order to support newer filetypes like wasm #105

### PR DESCRIPTION
**Pull request by jenweber**
## What Changed & Why

I updated the version of `mime` to `^2.3.1` in order to get the correct mime type assigned to wasm files. 2.x had breaking changes, which meant I changed some of the plugin methods.

Here are the breaking changes in `mime@2.x` that affected this plugin:
- `mime.lookup` was renamed to `mime.getType`
- `getType` returns null if there's not a match, whereas before it returned `default_type`.
- `default_type` is removed entirely. So, now a `getType`/`lookup` needs to have a fallback set by us, like `contentType = mime.getType(basePathUngzipped) || defaultType;`
- `mime.charsets.lookup` is removed. It was very rudimentary, so I just [copied the method](https://github.com/broofa/node-mime/blob/v1.x/mime.js#L101) into the codebase as `_mimeCharsetsLookup` 

I tested the deploy of my app and `wasm` files have the correct type now. Someone else should do a deploy with their apps just to be safe.

## Related issues
#105 

## PR Checklist
- [x] ~Add tests~
- [x] ~Add documentation~
- [x] ~Prefix documentation-only commits with [DOC]~

## People
@achambers @ghedamat

### CODE REVIEW

**Comment by jenweber** [comment]
In other news, I know more about the `mime` library than I ever wanted to know.

**Comment by lukemelia** [comment]
This looks excellent @jenweber! Thanks for the clear PR summary, too. I'll try it out with one of my apps and then we are good to merge from my perspective.

**Comment by lukemelia** [comment]
Test deploy went smoothly 👍

**Comment by ghedamat** [comment]
Thanks @jenweber ! This looks great to me as well! We'll try to merge and release a new version shortly.

Thanks also @lukemelia for jumping in!

**Review by achambers — APPROVED** [review]

**Comment by achambers** [comment]
Love your work @jenweber . Thanks a million 😸

**Comment by lukemelia** [comment]
Released as 1.3

**Comment by jenweber** [comment]
Y'all are so fast 🚀 Thanks for your help & the release!

**Pull request merged**
